# Generated by Django 5.0.7 on 2024-11-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(auto_now=True),
        ),
    ]
